# include:
#     - ./superset/docker-compose-image-tag.yml # loads the superset dashboard app

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    #   - API_URL=https://api.domain.com
    #   - DASHBOARD_URL=https://dashboard.domain.com
    # volumes:
    #   - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    external: true
