FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# COPY ./src/etl_pipeline.py /app/etl_pipeline.py
# COPY ./src/google_cloud_storage_manager.py /app/google_cloud_storage_manager.py

COPY ./src/ /app/src/ 
COPY .env /app/.env

CMD ["python", "-m", "src.etl_pipeline"]