name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create .env file
      run: |
        echo "GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }}" >> backend/.env
        echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> backend/.env
    - name: Build the Docker image
      run: docker build -f backend/Dockerfile -t python_selenium_single_image:$(date +%s) backend
